name: Minimal Octo Docker Smoketest

on:
  workflow_dispatch:

jobs:
  copy-debs:
    name: Copy .deb files
    runs-on: [self-hosted, windows, x64, octo]

    outputs:
      debs-present: ${{ steps.check.outputs.found }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: check
        name: Copy .deb files from temp
        shell: powershell
        run: |
          $temp = "${{ runner.workspace }}/temp"
          if (-not (Test-Path $temp)) {
            Write-Error "Temp folder not found: $temp"
            exit 1
          }

          $files = Get-ChildItem -Path $temp -Filter *.deb
          if (-not $files) {
            Write-Error "No .deb files found in temp!"
            exit 1
          }

          Copy-Item $temp\*.deb . -Force

          echo "found=true" >> $env:GITHUB_OUTPUT


  build-docker:
    name: Build Docker image (reused workflow)
    needs: copy-debs
    uses: ./.github/workflows/build_docker.yml
    with:
      image_name: "octo-test"
      dockerfile: ".github/docker/Dockerfile.octo-test"

  run-smoketest:
    name: Run Smoketest inside Docker
    needs: build-docker
    shell: powershell
    run: |
      cd test
      octo run smoketest.sh
