name: Run Smoketest

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - test/**
  pull_request:
    branches:
      - main

env:
  OCTO_TOKEN: test-token
  OCTO_SERVER: http://127.0.0.1:5000

jobs:
  run-smoketest:
    name: Run Smoketest
    runs-on: [self-hosted, windows, x64, octo]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Octo login
        run: |
          octo login --token ${{ env.OCTO_TOKEN }} --server ${{ env.OCTO_SERVER }}

      - name: Configure Docker
        run: |
          octo config --docker octo-test:latest

      - name: Run Smoketest
        run: |
          cd test
          chmod +x smoketest.sh
          octo run smoketest.sh
